name: Run JMeter Test on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  jmeter-test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Java 8 (required for JMeter)
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu' # A distribution of Java compatible with GitHub runners

      # Step 3: Download and Install Apache JMeter 5.6.3
      - name: Download Apache JMeter
        run: |
          curl -o apache-jmeter-5.6.3.zip https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.zip
          tar -xf apache-jmeter-5.6.3.zip
          echo "JMeter installed in $PWD/apache-jmeter-5.6.3"

      # Step 4: Run JMeter Script
      - name: Run JMeter Test
        run: |
          apache-jmeter-5.6.3/bin/jmeter.bat -n -t C:\php_test.jmx -l results1.jtl -e -o report
        shell: cmd # Use Windows shell for proper path handling  

      # Step 5: Upload Test Report and JTL file
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-report
          path: report
