name: JMeter CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  jmeter:
    runs-on: ubuntu-latest  # GitHub's virtual machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository

      - name: Install JMeter
        run: |
          wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xvzf apache-jmeter-5.6.3.tgz
          export PATH=$PATH:$PWD/apache-jmeter-5.5/bin  # Add JMeter to PATH
          echo "JMeter Installed Successfully"

      - name: Run JMeter Test
        run: |
          jmeter -n -t ./path/to/your/php_test.jmx -l results.jtl  # Run the JMeter script
        shell: bash

      - name: Generate JMeter Report
        run: |
          mkdir -p reports
          jmeter -g results.jtl -o reports/  # Generate the HTML report

      - name: Upload JMeter Report
        uses: actions/upload-artifact@v3
        with:
          name: JMeter-Report
          path: reports  # Upload the report as an artifact
